config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root 'overwatch_hero#index'
  resources :overwatch_character, only: %i[index show] do
    collection do
        get "search"
    end
  end
  get "/classes", to: "overwatch_hero#index", as: "overwatch_heroes"
  get "/show/:id", to: "overwatch_hero#show", as: "overwatch_characters"
  get "/search", to: "overwatch_hero#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/overwatch_character.rb
class OverwatchCharacter < ApplicationRecord
  paginates_per 8
  belongs_to :overwatch_class
  validates :name, presence: true
  validates :difficulty, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

app/models/overwatch_class.rb
class OverwatchClass < ApplicationRecord
  has_many :overwatch_characters
  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/overwatch_class_controller.rb
class OverwatchClassController < ApplicationController
  def index
    @hero = OverwatchCharacter.all
  end

  def show
    @show = OverwatchCharacter.find(params[:id])
  end

  def search
    @find = OverwatchCharacter.where("name LIKE ?", "%" + params[:q] + "%")
  end
end

app/controllers/overwatch_hero_controller.rb
class OverwatchHeroController < ApplicationController
  def index
    @hero = OverwatchCharacter.page params[:page]
  end

  def show
    @show = OverwatchCharacter.find(params[:id])
  end

  def search
    search = "%#{params[:q]}%"
    hero = "%#{params[:class]}%"

    if hero == ""
      @hero = OverwatchCharacter.where("name LIKE ?", search)
    else
      @hero = OverwatchCharacter.where("name LIKE ? AND overwatch_class_id LIKE ?", search, hero)
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/overwatch_hero_helper.rb
module OverwatchHeroHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<p>This website displays heroes from the game Overwatch. It was created using an API and is stored into tables inside a database, these tables are called characters and class.
For the characters table using name to grab the name of the hero, difficulty to grab the difficulty of the hero, image to grab the image, and description to grab the discription
of the character. The class table will only be grabing the hero's class which is defined by name on the table with a one to many relationship between the tables because you can
have one class but there are many characters in the class. Below shows an ERD rerpresentation of the tables and relationship between them.
</p>

 <%= image_tag "ERD.png" %>
<p>API used: <a href="https://github.com/isaacmillercodes/overwatch-hero-api" class="link-info">Overwatch API</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RailsOverwatchProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Overwatch Wiki</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= overwatch_heroes_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about/index">About</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="/search">
       <select class="form-control me-2" name="class" >
          <option value="">Select Class</option>
          <option value="1">Offense</option>
          <option value="2">Defense</option>
          <option value="3">Tank</option>
          <option value="4">Support</option>
        </select>
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search" >
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/overwatch_hero/index.html.erb
 <div>
  <h1 class = "text-center">Overwatch Heroes</h1>

  <div class="container grid">
    <% @hero.each do |m| %>
    <div class="g-col-3 card shadow p-3 mb-5 bg-body rounded ">
    <img src="<%= m.image %>" alt="<%= m.name %>" class ="img-fluid border">
    <a class="text-center" href="<%= overwatch_characters_path(m.id) %>"><%= m.name %></a>
    </div>
    <%end%>
  </div>
  <%= paginate @hero %>
</div>

app/views/overwatch_hero/search.html.erb
<h1 class = "text-center">Search Result</h1>
<div class = "container grid text-center">
  <%@hero.each do |m|%>
  <div class="g-col-3 card shadow p-3 mb-5 bg-body rounded text-center">
    <div>
      <H2><%= m.name %></H2>
      <img src="<%= m.image %>" alt="<%= m.name %>" class = "img-fluid">
      <p><%= m.description %></p>
      <p>Difficulty: <%= m.difficulty%></p>
      <p>Class Type: <%= m.overwatch_class.name%></p>
    </div>
  </div>
  <%end%>
</div>

app/views/overwatch_hero/show.html.erb
<div class ="text-center col-4 p-1 border border-primary shadow-lg p-3 mb-5 bg-body rounded">
  <H1><%= @show.name %></H1>
  <img src="<%= @show.image %>" alt="<%= @show.name %>">
  <p><%= @show.description %></p>
  <p>Difficulty: <%= @show.difficulty%></p>
  <p>Class Type: <%= @show.overwatch_class.name%></p>
</div>